import os

QDRANT_CLUSTER_URL = os.environ.get('QDRANT_CLUSTER_URL')
QDRANT_CLUSTER_TOKEN = os.environ.get('QDRANT_CLUSTER_TOKEN')

IMG_COLLECTION_NAME = os.environ.get('IMG_COLLECTION_NAME')
HAIKU_COLLECTION_NAME = os.environ.get('HAIKU_COLLECTION_NAME')
